
#ifndef TRACEGENERATOR_PAKETLOSSMODELTYPE_H
#define TRACEGENERATOR_PAKETLOSSMODELTYPE_H
enum PaketlossModelType {
    BERNOULLI,
    //Add new Models here:

    //
    MARKOV
};
#endif //TRACEGENERATOR_PAKETLOSSMODELTYPE_H
