tconfintlow <- function( gamma, x) {return(mean(x)+qt((1 - gamma ) / 2 ,length (x) - 1)* sd(x)/sqrt(length (x) ) )  }
tconfintup <- function( gamma, x) {return(mean(x)+qt(1-(1-gamma)/2 ,length(x)-1)*sd(x)/sqrt(length (x) ))}

distancesB <- read.table("Dokumente/Messung_13_12_18/Hinfahrt/AutomatischeAuswertung/BernoulliLeastSquaredDistances.txt")
distancesSG <- read.table("Dokumente/Messung_13_12_18/Hinfahrt/AutomatischeAuswertung/SimpleGilbertLeastSquaredDistances.txt")
distancesG <- read.table("Dokumente/Messung_13_12_18/Hinfahrt/AutomatischeAuswertung/GilbertLeastSquaredDistances.txt")
distancesGE <- read.table("Dokumente/Messung_13_12_18/Hinfahrt/AutomatischeAuswertung/GilbertElliotLeastSquaredDistances.txt")
distancesM <- read.table("Dokumente/Messung_13_12_18/Hinfahrt/AutomatischeAuswertung/MarkovLeastSquaredDistances.txt")
conflowB <-tconfintlow (0.95 , distancesB[,1]) 
confupB <-tconfintup (0.95 , distancesB[,1])
conflowSG <-tconfintlow (0.95 , distancesSG[,1]) 
confupSG <-tconfintup (0.95 , distancesSG[,1])
conflowG <-tconfintlow (0.95 , distancesG[,1]) 
confupG <-tconfintup (0.95 , distancesG[,1])
conflowGE <-tconfintlow (0.95 , distancesGE[,1]) 
confupGE <-tconfintup (0.95 , distancesGE[,1])
conflowM <-tconfintlow (0.95 , distancesM[,1]) 
confupM <-tconfintup (0.95 , distancesM[,1])
boxplot(distancesB[,1], distancesSG[,1], distancesG[,1], distancesGE[,1], distancesM[,1], main="Fitting Results - Least Squares", ylab="Squared Distance", names=c("Bernoulli", "Simple-Gilbert", "Gilbert", "Gilbert-Elliot", "Markov"), sub="Train OS-MS 13.12.2018 Least-Squared Distances")
#lines(c(0,5), c(9, 9), col="grey", lty=2)
#lines(c(0,5), c(9.2, 9.2), col="grey", lty=2)
#lines(c(0,5), c(9.4, 9.4), col="grey", lty=2)
#lines(c(0,5), c(9.6, 9.6), col="grey", lty=2)
#lines(c(0,5), c(9.8, 9.8), col="grey", lty=2)
#lines(c(0,5), c(10, 10), col="grey", lty=2)
#boxplot(bandwidthsKernel[,1], bandwidthsUsr[,1], bandwidthsKernelNeu[,1], bandwidthsUsrNeu[,1], main="10Mbit/s Datenrate", ylab="Goodput [Mbit/s]", names=c("FreeBSD nanosleep", "Usrsctp nanosleep", "FreeBSD while", "Usrsctp while"), sub="Paketgröße: 1000 Byte; 1 Datenpunkt besteht aus 1000 Paketen; 1000 Datenpunkte pro Boxplot", add=TRUE) #Linien hinter dem plot
lines(c(0.6,1.4),c(conflowB,conflowB), col="red", lty=1)
lines(c(0.6,1.4),c(confupB,confupB), col="red", lty=1)
lines(c(1.6,2.4),c(conflowSG,conflowSG), col="red", lty=1)
lines(c(1.6,2.4),c(confupSG,confupSG), col="red", lty=1)
lines(c(2.6,3.4),c(conflowG,conflowG), col="red", lty=1)
lines(c(2.6,3.4),c(confupG,confupG), col="red", lty=1)
lines(c(3.6,4.4),c(conflowGE,conflowGE), col="red", lty=1)
lines(c(3.6,4.4),c(confupGE,confupGE), col="red", lty=1)
lines(c(4.6,5.4),c(conflowM,conflowM), col="red", lty=1)
lines(c(4.6,5.4),c(confupM,confupM), col="red", lty=1)
legend("topright", lwd=1,lty=1,col="red",legend="95% Konfidenzintervall")