//
// Created by dennis on 31.01.19.
//

#ifndef TRACEGENERATOR_PACKETLOSSMODELTYPE_H
#define TRACEGENERATOR_PACKETLOSSMODELTYPE_H

enum PacketLossModelType {
    BERNOULLI,
    SIMPLE_GILBERT,
    GILBERT,
    GILBERT_ELLIOT,
    MARKOV
};

#endif //TRACEGENERATOR_PACKETLOSSMODELTYPE_H
